# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12iFDLzTgAKj2rCEprmR7WH-reHRDm3qg
"""

score = input().split()

countF = 0

min, max = int(score[0]), int(score[0])

for i in score:
  if int(i) < 60:
    countF += 1
  if int(i) < min:
    min = int(i)
  if int(i) > max:
    max = int(i)
print("不及格人數 : ", countF)
print("min : ", min)
print("max: ", max)